module:
    hugoVersion:
        extended: true  # æ˜¯å¦å¯ç”¨Hugoçš„æ‰©å±•åŠŸèƒ½ï¼Œè®¾ç½®ä¸ºtrueæ„å‘³ç€ä½¿ç”¨Hugoçš„å®Œæ•´ç‰ˆï¼Œæ”¯æŒæ›´å¤šåŠŸèƒ½
        min: "0.87.0"  # æœ€ä½æ”¯æŒçš„Hugoç‰ˆæœ¬ï¼Œç¡®ä¿ä½ çš„ç¯å¢ƒä½¿ç”¨çš„ç‰ˆæœ¬ä¸ä½äºæ­¤ç‰ˆæœ¬

params:
    mainSections:
        - post  # æŒ‡å®šä¸»é¡µä¸Šæ˜¾ç¤ºçš„ä¸»è¦éƒ¨åˆ†ï¼Œè¿™é‡Œè¡¨ç¤ºå±•ç¤º"post"éƒ¨åˆ†ï¼Œé€šå¸¸æ˜¯åšå®¢æ–‡ç« 
    featuredImageField: image  # è®¾ç½®æ–‡ç« çš„ç‰¹è‰²å›¾ç‰‡å­—æ®µï¼ŒæŒ‡ç¤ºHugoæ¨¡æ¿ä½¿ç”¨å“ªä¸ªå­—æ®µæ¥å±•ç¤ºæ–‡ç« çš„å°é¢å›¾
    rssFullContent: true  # å¯ç”¨å®Œæ•´å†…å®¹çš„RSSè®¢é˜…ï¼Œè®¾ç½®ä¸ºtrueè¡¨ç¤ºRSSä¸­å°†åŒ…å«æ–‡ç« çš„å®Œæ•´å†…å®¹

    favicon:  # è¿™ä¸ªå­—æ®µä¸ºç©ºï¼Œæ„å‘³ç€é»˜è®¤ä¸ä¼šè®¾ç½®ç«™ç‚¹çš„faviconå›¾æ ‡ã€‚ä½ å¯ä»¥å¡«å†™å›¾æ ‡è·¯å¾„ï¼Œä¾‹å¦‚ "favicon.ico"

    footer:
        since: 2025  # ç½‘ç«™åº•éƒ¨æ˜¾ç¤ºçš„èµ·å§‹å¹´ä»½ã€‚å¯ä»¥å¡«å¦‚ "2025" è¡¨ç¤ºç½‘ç«™ä»2025å¹´å¼€å§‹
        customText:  Danica Yang # è‡ªå®šä¹‰çš„æ–‡æœ¬æ˜¾ç¤ºåœ¨ç½‘ç«™åº•éƒ¨ï¼Œå¯ä»¥ç”¨äºæ˜¾ç¤ºç‰ˆæƒå£°æ˜æˆ–å…¶ä»–ä¿¡æ¯

    dateFormat:
        published: Jan 02, 2006  # æ–‡ç« å‘å¸ƒæ—¶é—´çš„æ—¥æœŸæ ¼å¼ï¼Œå¯ä»¥æ ¹æ®éœ€è¦ä¿®æ”¹æ ¼å¼
        lastUpdated: Jan 02, 2006 15:04 MST  # æ–‡ç« æœ€åæ›´æ–°æ—¶é—´çš„æ—¥æœŸæ ¼å¼

    sidebar:
        compact: false  # æ˜¯å¦å¯ç”¨ç´§å‡‘å‹ä¾§è¾¹æ ï¼Œè®¾ç½®ä¸ºfalseè¡¨ç¤ºä¾§è¾¹æ å†…å®¹è¾ƒä¸ºå®½æ¾
        emoji:  ğŸ¥°# å¯ä»¥è®¾ç½®ä¸ºä½ å–œæ¬¢çš„è¡¨æƒ…ï¼Œé»˜è®¤ä¸ºç©º
        subtitle:  # åœ¨ä¾§è¾¹æ ä¸­æ˜¾ç¤ºçš„å‰¯æ ‡é¢˜
        avatar:
            enabled: true  # æ˜¯å¦å¯ç”¨å¤´åƒæ˜¾ç¤ºï¼Œè®¾ç½®ä¸ºtrueè¡¨ç¤ºä¼šæ˜¾ç¤ºå¤´åƒ
            local: true  # æ˜¯å¦ä½¿ç”¨æœ¬åœ°å¤´åƒï¼Œè®¾ç½®ä¸ºtrueè¡¨ç¤ºå¤´åƒä»æœ¬åœ°åŠ è½½
            src: "Danica/themes/stack/images/touxiang.jpg"  # å¤´åƒçš„è·¯å¾„ï¼Œç¡®ä¿è·¯å¾„æ­£ç¡®å¹¶ä¸”æ–‡ä»¶å­˜åœ¨

    article:
        headingAnchor: false  # æ˜¯å¦å¯ç”¨æ–‡ç« æ ‡é¢˜é”šç‚¹ï¼Œè®¾ç½®ä¸ºfalseè¡¨ç¤ºæ ‡é¢˜ä¸å¯ç›´æ¥é“¾æ¥
        math: true  # æ˜¯å¦å¯ç”¨æ•°å­¦å…¬å¼æ”¯æŒï¼Œè®¾ç½®ä¸ºfalseè¡¨ç¤ºä¸æ”¯æŒ
        toc: true  # æ˜¯å¦åœ¨æ–‡ç« ä¸­å¯ç”¨ç›®å½•ï¼ˆTable of Contentsï¼‰ï¼Œè®¾ç½®ä¸ºtrueè¡¨ç¤ºå¯ç”¨
        readingTime: true  # æ˜¯å¦åœ¨æ–‡ç« é¡µé¢æ˜¾ç¤ºé¢„è®¡é˜…è¯»æ—¶é—´ï¼Œè®¾ç½®ä¸ºtrueè¡¨ç¤ºæ˜¾ç¤º
        license:
            enabled: false  # æ˜¯å¦å¯ç”¨ç‰ˆæƒè®¸å¯ï¼Œè®¾ç½®ä¸ºfalseè¡¨ç¤ºä¸æ˜¾ç¤ºç‰ˆæƒå£°æ˜
            default: Licensed under CC BY-NC-SA 4.0  # é»˜è®¤çš„ç‰ˆæƒè®¸å¯ç±»å‹

    comments:
        enabled: false  # æ˜¯å¦å¯ç”¨è¯„è®ºåŠŸèƒ½ï¼Œè®¾ç½®ä¸ºfalseè¡¨ç¤ºä¸å¯ç”¨
        provider: disqus  # è®¾ç½®è¯„è®ºæä¾›å•†ï¼Œä½¿ç”¨Disqusä½œä¸ºè¯„è®ºç³»ç»Ÿ

        disqusjs:
            shortname:  disqus_q915XihCEb # Disqusçš„çŸ­åç§°ï¼Œéœ€è¦ä»Disqusç½‘ç«™ä¸Šè·å–
            apiUrl:  https://disqus.com/api/3.0/ # Disqus API URL
            apiKey:  # Disqus API å¯†é’¥
            admin:  # Disqusç®¡ç†å‘˜ç”¨æˆ·å
            adminLabel:  # ç®¡ç†å‘˜æ ‡ç­¾

        utterances:
            repo:  # Utterancesè¯„è®ºç³»ç»Ÿæ‰€ä½¿ç”¨çš„GitHubä»“åº“
            issueTerm: pathname  # ç”¨æ¥æ˜ å°„è¯„è®ºçš„è·¯å¾„æˆ–é¡µé¢
            label:  # è¯„è®ºæ ‡ç­¾

        # å¯ä»¥é€‰æ‹©å…¶ä»–è¯„è®ºç³»ç»Ÿé…ç½®ï¼Œä¾‹å¦‚remark42, vssueç­‰ï¼Œæ¯ä¸ªç³»ç»Ÿçš„é…ç½®æ–¹å¼ä¸åŒï¼Œéœ€è¦æä¾›ç›¸åº”çš„APIå¯†é’¥æˆ–ä»“åº“ä¿¡æ¯

        widgets:
            homepage:
                - "æœ€è¿‘æ–‡ç« "  # è¿™ä¸ªä½ç½®å¯ä»¥è®¾ç½®ä¸ºæ˜¾ç¤ºæœ€è¿‘çš„å‡ ç¯‡æ–‡ç« 
                - "çƒ­é—¨æ ‡ç­¾"  # ä¾‹å¦‚å¯ä»¥æ˜¾ç¤ºå¸¸è§çš„æ ‡ç­¾
            page:
                - "å…³äºæˆ‘"  # åœ¨é¡µé¢ä¾§è¾¹æ ä¸­æ˜¾ç¤ºä¸ªäººé¡µé¢é“¾æ¥

    opengraph:
        twitter:
            site:  # å¡«å†™ä½ çš„Twitterç”¨æˆ·åï¼Œè®¾ç½®åOpenGraphå…ƒæ•°æ®å°†åŒ…å«Twitterä¿¡æ¯
            card: summary_large_image  # Twitterå¡ç‰‡ç±»å‹ï¼Œè¡¨ç¤ºå±•ç¤ºå¤§å›¾

    defaultImage:
        opengraph:
            enabled: false  # æ˜¯å¦å¯ç”¨é»˜è®¤çš„OpenGraphå›¾ç‰‡ï¼Œè®¾ç½®ä¸ºfalseè¡¨ç¤ºä¸å¯ç”¨
            local: true  # æ˜¯å¦ä½¿ç”¨æœ¬åœ°å›¾ç‰‡ï¼Œè®¾ç½®ä¸ºfalseè¡¨ç¤ºä¸ä½¿ç”¨æœ¬åœ°å›¾ç‰‡
            src:  C:\Users\æ¨æ‚¦\Danica\themes\stack\images # å¦‚æœå¯ç”¨é»˜è®¤å›¾ç‰‡ï¼Œå¯ä»¥åœ¨è¿™é‡Œæä¾›å›¾ç‰‡è·¯å¾„

    colorScheme:
        toggle: true  # æ˜¯å¦å¯ç”¨ä¸»é¢˜åˆ‡æ¢æŒ‰é’®ï¼Œè®¾ç½®ä¸ºtrueè¡¨ç¤ºç”¨æˆ·å¯ä»¥åˆ‡æ¢ä¸»é¢˜ï¼ˆå¦‚æ·±è‰²å’Œæµ…è‰²æ¨¡å¼ï¼‰
        default: dark  # é»˜è®¤çš„ä¸»é¢˜ï¼Œè®¾ç½®ä¸ºautoè¡¨ç¤ºæ ¹æ®ç”¨æˆ·ç³»ç»Ÿçš„ä¸»é¢˜è‡ªåŠ¨åˆ‡æ¢

    imageProcessing:
        cover:
            enabled: true  # æ˜¯å¦å¯ç”¨å°é¢å›¾ç‰‡å¤„ç†ï¼Œè®¾ç½®ä¸ºtrueè¡¨ç¤ºå¯¹å°é¢å›¾è¿›è¡Œå¤„ç†ï¼ˆå¦‚è£å‰ªã€å‹ç¼©ç­‰ï¼‰
        content:
            enabled: true  # æ˜¯å¦å¯ç”¨å†…å®¹å›¾ç‰‡å¤„ç†ï¼Œè®¾ç½®ä¸ºtrueè¡¨ç¤ºå¯¹æ­£æ–‡ä¸­çš„å›¾ç‰‡è¿›è¡Œå¤„ç†
